/*
=========================
DO NOT EDIT THIS FILE!!!!
=========================
*/

window.TaskListView = Backbone.View.extend({
  
  className: 'container',

  initialize: function() {
    // instantiate the tasks collection, with some initial tasks
    this.collection = new Tasks(taskData);

    // listen to the collection for changes
    this.collection.on('completed', this.render, this);

    // initialize our element
    this.$el.append($("<div>Remaining tasks: <span class='tasks-remaining'></span></div><br /><div class='task-list'></div>"));
    this.render();
  },

  render: function() {
    // clear the task list before re-draw
    this.$('.task-list').children().detach();
    // re-draw the list of tasks by mapping over this.collection
    this.$('.task-list').append(
      this.collection.map(function(task) {
        return new TaskView({ model: task }).render();
      })
    );
    // update span to show num of tasks remaining by calling tasksRemaining() on collection
    this.$('.tasks-remaining').html(this.collection.countIncomplete());

    return this.$el;
  },

});
